# Generated by Django 5.2.11 on 2026-04-14 06:32

import django.utils.timezone
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_cart_id_alter_customer_id_alter_order_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="battery",
            field=models.CharField(
                blank=True, help_text="e.g., 72 Wh, Up to 10 hrs", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="delivery_text",
            field=models.CharField(
                blank=True,
                default="Free delivery by Tomorrow. In Stock",
                help_text="e.g., Free delivery by Tomorrow. In Stock",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="display",
            field=models.CharField(
                blank=True, help_text='e.g., 15.6" FHD IPS 144Hz', max_length=200
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="emi_available",
            field=models.BooleanField(default=False, verbose_name="EMI Available"),
        ),
        migrations.AddField(
            model_name="product",
            name="emi_text",
            field=models.CharField(
                blank=True,
                help_text="e.g., EMI from 2,533/month. No Cost EMI available",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="features",
            field=models.TextField(
                blank=True,
                help_text="Enter features separated by commas. e.g., Backlit KB, Thunderbolt 4, WI-FI 6E, Fingerprint",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="free_delivery",
            field=models.BooleanField(default=True, verbose_name="Free Delivery"),
        ),
        migrations.AddField(
            model_name="product",
            name="graphics",
            field=models.CharField(
                blank=True, help_text="e.g., NVIDIA RTX 4050", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="in_stock",
            field=models.BooleanField(default=True, verbose_name="In Stock"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_assured",
            field=models.BooleanField(
                default=True, verbose_name="Show 'TechNova Assured' badge"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Show 'NEW' badge"),
        ),
        migrations.AddField(
            model_name="product",
            name="offer_text",
            field=models.CharField(
                blank=True,
                help_text="e.g., 10% off with HDFC / ICICI cards",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="original_price",
            field=models.IntegerField(
                blank=True,
                help_text="Original price before discount (leave blank if no discount)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="os",
            field=models.CharField(
                blank=True,
                help_text="e.g., Windows 11 Home",
                max_length=100,
                verbose_name="Operating System",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="processor",
            field=models.CharField(
                blank=True, help_text="e.g., Intel Core i7-13700H", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="ram",
            field=models.CharField(
                blank=True, help_text="e.g., 16 GB DDR5", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(
                decimal_places=1, default=0.0, help_text="e.g., 4.8", max_digits=3
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="rating_count",
            field=models.IntegerField(default=0, help_text="Number of ratings"),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_count",
            field=models.IntegerField(default=10, help_text="Number of items in stock"),
        ),
        migrations.AddField(
            model_name="product",
            name="storage",
            field=models.CharField(
                blank=True, help_text="e.g., 512 GB NVMe SSD", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="product",
            name="weight",
            field=models.CharField(blank=True, help_text="e.g., 1.9 kg", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=store.models.product_image_path
            ),
        ),
    ]
